### ISSUE TITLE
start_matlab timeout error

### ISSUE THREAD

**Issue by craig-willis** [cropsinsilico/cis_interface#40]
When running the MeM model, we are frequently but intermittently seeing the following error:
```
INFO:runner.startDrivers[330]:CisRunner(runner): Starting I/O drivers and models on system craig-willis-20181126-154001-544735-5lms7 in namespace cis_interface with rank 0
/opt/conda/lib/python3.6/site-packages/cis_interface/serialize/__init__.py:828: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  names=names, **np_kws)
ERROR:runner.startDrivers[359]:CisRunner(runner): MeM did not start
Creating user config file: "/home/jovyan/.cis_interface.cfg".
cisrun exception: <class 'Exception'>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/command_line.py", line 19, in cisrun
    cisRunner.run()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/runner.py", line 171, in run
    self.startDrivers()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/runner.py", line 357, in startDrivers
    d.start()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/tools.py", line 867, in start
    self.before_start()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/drivers/MatlabModelDriver.py", line 371, in before_start
    self.start_matlab()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/drivers/MatlabModelDriver.py", line 333, in start_matlab
    self.screen_session, self.mlsession = start_matlab()
  File "/opt/conda/lib/python3.6/site-packages/cis_interface/drivers/MatlabModelDriver.py", line 90, in start_matlab
    raise Exception("start_matlab timed out at %f s" % T.elapsed)
Exception: start_matlab timed out at 10.017912 s
```

It's possible that this is caused by the 10s timeout:

https://github.com/cropsinsilico/cis_interface/blob/da375e49c79aeba70b4a735c03c6f42361e2d51e/cis_interface/drivers/MatlabModelDriver.py#L106

@langmm  could we parameterize the timeout value or at least allow it to be overridden by environment?  On Jetstream in Docker, MATLAB startup is likely > 10 s.

**Comment by langmm** [comment]
The startup time has been parameterized and can now be customized via the `startup_waittime_s` variable in the `matlab` section of the yggconfig file (see description of config file [here](https://cropsinsilico.github.io/yggdrasil/config.html)).
